//POSTS CONSTANTS
//Posts states
export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_REQUEST_FAILED = 'GET_POSTS_REQUEST_FAILED';
export const GET_POSTS_REQUEST_SUCCESS = 'GET_POSTS_REQUEST_SUCCESS';

//POST CONSTANTS
//Post states
export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_REQUEST_FAILED = 'GET_POST_REQUEST_FAILED';
export const GET_POST_REQUEST_SUCCESS = 'GET_POST_REQUEST_SUCCESS';
