export const GET_COMMENTS_REQUEST = 'GET_POST_REQUEST';
export const GET_COMMENTS_REQUEST_FAILED = 'GET_COMMENTS_REQUEST_FAILED';
export const GET_COMMENTS_REQUEST_SUCCESS = 'GET_COMMENTS_REQUEST_SUCCESS';

export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_REQUEST_FAILED = 'POST_COMMENT_REQUEST_FAILED';
export const POST_COMMENT_REQUEST_SUCCESS = 'POST_COMMENT_REQUEST_SUCCESS';

export const OPEN_COMMENT_FORM = 'OPEN_COMMENT_FORM';
export const CLOSE_COMMENT_FORM = 'CLOSE_COMMENT_FORM';
